### ISSUE TITLE
Equivalence

### ISSUE THREAD

**Issue by robpalme** [achingbrain/esm-vs-cjs#1]
The benchmark does not seem to be doing equivalent work.

```ts
import cjs from './cjs.cjs'
import { ESMClass } from './esm.js'

const CJSClass = cjs.CJSClass
```

We could change this so both classes are stored in a const binding.

```ts
import cjs from './cjs.cjs'
import * as esm from './esm.js'

const CJSClass = cjs.CJSClass
const ESMClass = esm.ESMClass
```

**Comment by achingbrain** [comment]
I've updated the benchmarks to use a variety of different import styles.  The README has the full results but the TLDR is to use node 14 and const bindings everywhere...
